### ISSUE TITLE
Changes in Tesla API calls

### ISSUE THREAD

**Issue by rhodesman** [rhodesman/teslaPowerDash#19]
As of earlier this week it looks like Tesla has changed the way to access their API.  It will require me to rebuild the entire middleware software to accommodate the new protocols they now have in place.  

Just know I am aware of the issue and am trying to build a solution that addresses it and the other issues with the middleware that were brought to my attention.

**Comment by caseybecking** [comment]
Just for clarification - this issue will cause the data to not populate into the database correct?

**Comment by Here-Be-Dragons** [comment]
I have my dashboard functional again, using Vince Loschiavo's script with a slight modification at the bottom.  Note that in order for this to work, you have to add to the telegraf config.

Vince's original script: https://raw.githubusercontent.com/vloschiavo/powerwall2/master/samples/powerwallstats.sh
My modification, adding a few lines to the bottom: https://gist.github.com/Here-Be-Dragons/fb51de47c84a6ad0426175ab08295235

The new telegraf snippet (I only had to add the `headers` line:)
```toml
 [[inputs.http]]
   urls = [
     "https://192.168.1.140/api/meters/aggregates",
     "https://192.168.1.140/api/system_status/soe",
     "https://192.168.1.140/api/meters/solar",
     "https://192.168.1.140/api/sitemaster",
     "https://192.168.1.140/api/system_status/grid_status",
     "https://192.168.1.140/api/status"
   ]
    method = "GET"
    insecure_skip_verify = true
    timeout = "5s"
    data_format = "json"
    headers = {"Cookie" = "AuthCookie=abcd; UserRecord=efgh"}
```
Once that file exists, toss my version of Vince's script into `/etc/cron.hourly/` and `chmod +x` it so it can be executed, and then your (Linux) OS will check the cookie hourly, replacing as needed.
